// ESLint 9 flat config. Next's own flat config (core web vitals + its TypeScript rules) covers all
// files; typescript-eslint's type-aware recommended rules cover src/, scripts/ and tests/. Generated
// files are ignored: regenerate them (`npm run generate:types`, `generate:importmap`,
// `payload migrate:create`) instead of editing them. One exception: a new migration's generated
// down() needs a hand edit (docs/gotchas.md, Migrations).
import { defineConfig, globalIgnores } from 'eslint/config';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import tseslint from 'typescript-eslint';

export default defineConfig(
  globalIgnores([
    // Build output, local uploads and Next's generated type file
    '.next/**',
    'out/**',
    'build/**',
    'coverage/**',
    'media/**',
    'next-env.d.ts',
    // Generated by Payload
    'src/payload-types.ts',
    'src/payload-generated-schema.ts',
    'src/app/(payload)/**',
    'src/migrations/**',
  ]),

  {
    linterOptions: { reportUnusedDisableDirectives: 'error' },
  },

  nextCoreWebVitals,
  nextTypescript,

  // Type-aware rules for the CMS source (config, collections, env) and for the scripts and test
  // setup that create and drop databases and buckets (floating promises, unsafe `any`). Root config
  // files keep Next's rules only: Next types its webpack hook with `any`.
  {
    files: ['src/**/*.{ts,tsx}', 'scripts/**/*.ts', 'tests/**/*.ts'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
  },

  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      // next/typescript only warns; an unused binding fails the lint unless it starts with `_`.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
);
